name: action_cable_stream
version: 1.0.1
description: >-
  ActionCable client port in dart using streams, available in web, dartVM and flutter.
homepage: https://github.com/kwent/actioncable_stream_dart
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  rxdart: ^0.27.7
  web_socket_channel: ^2.2.0
